language: node_js
node_js:
- '0.10'
before_deploy:
 - git config --global user.email "builds@travis-ci.com"
 - git config --global user.name "Travis CI"
 - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
 - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
 - ls -R
deploy:
  provider: releases
  api_key:
    secure: LifWcMvVdfecAE8MwECByqgoJZzjzlbO+0TedFZZ/zP+llfE024QAWluSpL6VrZTvqiAgPUj1M7H2YhxIGfoecnBZSHR+65BMDABFkQ/5Q+yH12iRDLK9bvjr+ToXSe7ia/MAtr08Ma9Z4yCNIOrnb003Liupq/NgNWJL+KQeQk=
  file:
    - dist\indexeddbmock.js
    - dist\indexeddbmock.min.js  
  skip_cleanup: true

  on:
    repo: kristofdegrave/indexedDBmock
    tag: false
    all_branches: true
